
baseURL = "https://dantelore.com"
languageCode = "en-gb"
title = "Dante Lore"

# Site settings
themesDir = "themes"
theme = "cactus"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-75202-6"

# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[markup.goldmark.renderer]
      unsafe = true

[params]
      name = "Dan Taylor"
      description = "Big Data, amateur welding, improvised woodwork and high adventure!"
      bio = "Still crushin' it"
      twitter = "DanteLore"
      enableRSS = false

      home = "home"
      title404 = ""
      subtitle404 = ""

      # Integrate Javascript files or stylesheets by adding the url to the external assets or by
      # linking local files with their path relative to the static folder, e.g. "css/styles.css"
      customCSS = ["css/styles.css"]
      customJS  = []

      socialIconStyle = "circle"
