baseURL = "http://dantelore.com/"
languageCode = "en-gb"
title = "Dante Lore"

# Site settings
baseurl = "https://dantelore.com/"
themesDir = "themes"
#languageCode = "en-gb"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[markup.goldmark.renderer]
      unsafe = true

[params]
      name = "Dan Taylor"
      description = "Big Data, amateur welding, improvised woodwork and high adventure!"
      bio = "Still crushin' it"
      # Enter optionally your twitter account
      twitter = "DanteLore"
      enableRSS = true

      # Integrate Javascript files or stylesheets by adding the url to the external assets or by
      # linking local files with their path relative to the static folder, e.g. "css/styles.css"
      customCSS = ["css/styles.css"]
      customJS  = []
